graph LR
    subgraph Projects["Services & Projects"]
        NuGet_Packaging_Test["NuGet.Packaging.Test"]
    end
    subgraph APIs["API Routes"]
        url_Aa_nuspec(["Aa.nuspec"])
    end
    url_Aa_nuspec -.->|consume| NuGet_Packaging_Test