graph TD
    subgraph sg_Presentation["Presentation (4)"]
        NuGet_PackageManagement_PowerShellCmdlets["NuGet.PackageManagement.PowerShellCmdlets"]
        NuGet_PackageManagement_UI["NuGet.PackageManagement.UI"]
        NuGet_PackageManagement_UI_Test["NuGet.PackageManagement.UI.Test"]
        NuGet_PackageManagement_UI_TestContract["NuGet.PackageManagement.UI.TestContract"]
    end
    subgraph sg_DataAccess["DataAccess (9)"]
        grp_NuGet["NuGet (8)"]
        Microsoft_Internal_NuGet_Testing_SignedPackages["Microsoft.Internal.NuGet.Testing.SignedPackages"]
    end
    subgraph sg_Infrastructure["Infrastructure (2)"]
        NuGet_VisualStudio_Common["NuGet.VisualStudio.Common"]
        VisualStudio_Test_Utility["VisualStudio.Test.Utility"]
    end
    subgraph sg_Unclassified["Unclassified (1)"]
        NuGet_Console["NuGet.Console"]
    end
    NuGet_PackageManagement_UI_Test --> grp_NuGet
    NuGet_PackageManagement_UI --> grp_NuGet
    NuGet_PackageManagement_UI_Test --> VisualStudio_Test_Utility
    VisualStudio_Test_Utility --> Microsoft_Internal_NuGet_Testing_SignedPackages
    VisualStudio_Test_Utility --> grp_NuGet
    NuGet_PackageManagement_UI_TestContract --> NuGet_PackageManagement_UI
    Microsoft_Internal_NuGet_Testing_SignedPackages --> grp_NuGet
    grp_NuGet --> NuGet_VisualStudio_Common
    NuGet_VisualStudio_Common --> grp_NuGet
    NuGet_PackageManagement_PowerShellCmdlets --> NuGet_Console
    NuGet_Console --> NuGet_PackageManagement_UI