graph TD
    NuGet_PackageManagement_UI["NuGet.PackageManagement.UI\n(Presentation)"]
    NuGet_PackageManagement_VisualStudio["NuGet.PackageManagement.VisualStudio\n(DataAccess)"]
    NuGet_PackageManagement_UI --> NuGet_PackageManagement_VisualStudio