graph LR
    NuGet_PackageManagement_UI_Test["NuGet.PackageManagement.UI.Test\n(Presentation)"]
    NuGet_PackageManagement_VisualStudio["NuGet.PackageManagement.VisualStudio\n(DataAccess)"]
    NuGet_PackageManagement_UI_Test --> NuGet_PackageManagement_VisualStudio
    NuGet_Indexing["NuGet.Indexing\n(DataAccess)"]
    NuGet_PackageManagement_VisualStudio --> NuGet_Indexing