graph LR
    subgraph Applications
        NuGet_Client_NuGet_CommandLine["NuGet.CommandLine"]
        NuGet_Client_NuGet_CommandLine_XPlat["NuGet.CommandLine.XPlat"]
        NuGet_Client_ensure_nupkg_dependencies_on_source["ensure-nupkg-dependencies-on-source"]
        NuGet_Client_ship_public_apis["ship-public-apis"]
    end
    subgraph DataSources
        datasource_NuGet_Client_Redis_Read[("Redis.Read")]
        datasource_NuGet_Client_Dapper_Execute[("Dapper.Execute")]
        datasource_NuGet_Client_Redis_Write[("Redis.Write")]
        datasource_NuGet_Client_MongoDB_Read[("MongoDB.Read")]
        datasource_NuGet_Client_SqlClient[("SqlClient")]
        datasource_NuGet_Client_Kafka_Consumer[("Kafka.Consumer")]
        datasource_NuGet_Client_SQL_Select[("SQL.Select")]
        datasource_NuGet_Client_SQL_Delete[("SQL.Delete")]
    end