graph LR
    NuGet_PackageManagement_UI_Test["NuGet.PackageManagement.UI.Test\n(Presentation)"]
    VisualStudio_Test_Utility["VisualStudio.Test.Utility\n(Infrastructure)"]
    NuGet_PackageManagement_UI_Test --> VisualStudio_Test_Utility
    NuGet_PackageManagement["NuGet.PackageManagement\n(DataAccess)"]
    VisualStudio_Test_Utility --> NuGet_PackageManagement
    NuGet_Commands["NuGet.Commands\n(DataAccess)"]
    NuGet_PackageManagement --> NuGet_Commands