graph LR
    NuGet_PackageManagement_UI["NuGet.PackageManagement.UI\n(Presentation)"]
    NuGet_PackageManagement_VisualStudio["NuGet.PackageManagement.VisualStudio\n(DataAccess)"]
    NuGet_PackageManagement_UI --> NuGet_PackageManagement_VisualStudio
    NuGet_VisualStudio_Common["NuGet.VisualStudio.Common\n(Infrastructure)"]
    NuGet_PackageManagement_VisualStudio --> NuGet_VisualStudio_Common
    NuGet_PackageManagement["NuGet.PackageManagement\n(DataAccess)"]
    NuGet_VisualStudio_Common --> NuGet_PackageManagement