graph LR
    subgraph webapp["Webapp"]
        src_WebApp["WebApp"]
        src_Identity_API["Identity.API"]
        src_Catalog_API["Catalog.API"]
        src_WebAppComponents["WebAppComponents"]
        src_PaymentProcessor["PaymentProcessor"]
        src_Basket_API["Basket.API"]
        src_Ordering_API["Ordering.API"]
        src_Webhooks_API["Webhooks.API"]
    end
    ext_service(["Service (1)"])
    ext_library(["Library (4)"])
    ext_application(["Application (2)"])
    ext_test(["Test (4)"])
    src_WebApp --> src_WebAppComponents
    src_WebApp -.-> ext_service
    src_WebApp -.-> ext_library
    src_Identity_API -.-> ext_service
    src_Catalog_API -.-> ext_library
    src_Catalog_API -.-> ext_service
    ext_application -.-> src_Basket_API
    ext_application -.-> src_Catalog_API
    ext_application -.-> src_Identity_API
    ext_application -.-> src_Ordering_API
    ext_application -.-> src_PaymentProcessor
    ext_application -.-> src_Webhooks_API
    ext_application -.-> src_WebApp
    src_PaymentProcessor -.-> ext_service
    src_PaymentProcessor -.-> ext_library
    ext_application -.-> src_WebAppComponents
    src_Basket_API -.-> ext_service
    src_Basket_API -.-> ext_library
    src_Ordering_API -.-> ext_library
    src_Ordering_API -.-> ext_service
    src_Webhooks_API -.-> ext_library
    src_Webhooks_API -.-> ext_service
    ext_test -.-> src_Ordering_API
    ext_test -.-> src_Identity_API
    ext_test -.-> src_Catalog_API
    ext_test -.-> src_Basket_API