graph LR
    subgraph Applications
        src_KurrentDB_Plugins_Api_V2["KurrentDB.Plugins.Api.V2"]
        src_KurrentDB_Diagnostics_LogsEndpointPlugin["KurrentDB.Diagnostics.LogsEndpointPlugin"]
        src_KurrentDB_Security_EncryptionAtRest["KurrentDB.Security.EncryptionAtRest"]
        src_KurrentDB_Api_V2["KurrentDB.Api.V2"]
        src_KurrentDB_Auth_OAuth["KurrentDB.Auth.OAuth"]
        src_KurrentDB_MicroBenchmarks["KurrentDB.MicroBenchmarks"]
        src_KurrentDB_Plugins_SchemaRegistry["KurrentDB.Plugins.SchemaRegistry"]
        src_KurrentDB_Auth_Ldaps["KurrentDB.Auth.Ldaps"]
        src_KurrentDB_ClusterNode_Web["KurrentDB.ClusterNode.Web"]
        src_KurrentDB_Auth_LegacyAuthorizationWithStreamAuthorizationDisabled["KurrentDB.Auth.LegacyAuthorizationWithStreamAuthorizationDisabled"]
        src_KurrentDB_Auth_UserCertificates["KurrentDB.Auth.UserCertificates"]
        src_KurrentDB["KurrentDB"]
    end
    subgraph DataSources
        datasource_src_Kafka_Consumer[("Kafka.Consumer")]
        datasource_src_Redis_Read[("Redis.Read")]
        datasource_src_Redis_Write[("Redis.Write")]
        datasource_src_Kafka_Topic[("Kafka.Topic")]
        datasource_src_Dapper_Execute[("Dapper.Execute")]
        datasource_src_MongoDB_Read[("MongoDB.Read")]
        datasource_src_Kafka_Producer[("Kafka.Producer")]
        datasource_src_SQL_CreateTable[("SQL.CreateTable")]
        datasource_src_SQL_Select[("SQL.Select")]
        datasource_src_SQL_Insert[("SQL.Insert")]
        datasource_src_SQL_Delete[("SQL.Delete")]
        datasource_src_Dapper_Query[("Dapper.Query")]
        datasource_src_MongoDB_Write[("MongoDB.Write")]
    end