graph LR
    subgraph Microsoft["Microsoft"]
        nuget_Microsoft_OpenApi_Readers["Microsoft.OpenApi.Readers<br/>"]
        nuget_Microsoft_AspNetCore_TestHost["Microsoft.AspNetCore.TestHost<br/>"]
        nuget_Microsoft_Extensions_Diagnostics_Testing["Microsoft.Extensions.Diagnostics.Testing<br/>"]
        nuget_Microsoft_AspNetCore_Grpc_JsonTranscoding["Microsoft.AspNetCore.Grpc.JsonTranscoding<br/>"]
        nuget_Microsoft_Extensions_TimeProvider_Testing["Microsoft.Extensions.TimeProvider.Testing<br/>"]
        nuget_Microsoft_Extensions_Configuration_EnvironmentVariables["Microsoft.Extensions.Configuration.EnvironmentVariables<br/>"]
        nuget_Microsoft_Extensions_Hosting_Abstractions["Microsoft.Extensions.Hosting.Abstractions<br/>"]
        nuget_Microsoft_AspNetCore_Mvc_Testing["Microsoft.AspNetCore.Mvc.Testing<br/>"]
        Microsoft_more["... +21 more"]
    end
    subgraph Serilog["Serilog"]
        nuget_Serilog["Serilog<br/>"]
        nuget_Serilog_Sinks_OpenTelemetry["Serilog.Sinks.OpenTelemetry<br/>"]
        nuget_Serilog_Sinks_InMemory["Serilog.Sinks.InMemory<br/>"]
        nuget_Serilog_AspNetCore["Serilog.AspNetCore<br/>"]
        nuget_Serilog_Sinks_TextWriter["Serilog.Sinks.TextWriter<br/>"]
        nuget_Serilog_Enrichers_Thread["Serilog.Enrichers.Thread<br/>"]
        nuget_Serilog_Enrichers_Environment["Serilog.Enrichers.Environment<br/>"]
        nuget_Serilog_Enrichers_Process["Serilog.Enrichers.Process<br/>"]
        Serilog_more["... +15 more"]
    end
    subgraph Kurrent["Kurrent"]
        nuget_Kurrent_Surge["Kurrent.Surge<br/>"]
        nuget_Kurrent_Surge_Core["Kurrent.Surge.Core<br/>"]
        nuget_Kurrent_Quack["Kurrent.Quack<br/>"]
        nuget_Kurrent_Surge_DuckDB["Kurrent.Surge.DuckDB<br/>"]
        nuget_Kurrent_Surge_DataProtection["Kurrent.Surge.DataProtection<br/>"]
        nuget_Kurrent_Connectors_Elasticsearch["Kurrent.Connectors.Elasticsearch<br/>"]
        nuget_Kurrent_Connectors_Http["Kurrent.Connectors.Http<br/>"]
        nuget_Kurrent_Connectors_Kafka["Kurrent.Connectors.Kafka<br/>"]
        Kurrent_more["... +4 more"]
    end
    subgraph System["System"]
        nuget_System_Linq_Async["System.Linq.Async<br/>"]
        nuget_System_Diagnostics_PerformanceCounter["System.Diagnostics.PerformanceCounter<br/>"]
        nuget_System_ComponentModel_Composition["System.ComponentModel.Composition<br/>"]
        nuget_System_Reactive["System.Reactive<br/>"]
        nuget_System_IdentityModel_Tokens_Jwt["System.IdentityModel.Tokens.Jwt<br/>"]
        nuget_System_ServiceModel_Http["System.ServiceModel.Http<br/>"]
        nuget_System_Security_Cryptography_Pkcs["System.Security.Cryptography.Pkcs<br/>"]
        nuget_System_Security_Cryptography_Xml["System.Security.Cryptography.Xml<br/>"]
        System_more["... +1 more"]
    end
    subgraph Grpc["Grpc"]
        nuget_Grpc_Net_Client["Grpc.Net.Client<br/>"]
        nuget_Grpc_StatusProto["Grpc.StatusProto<br/>"]
        nuget_Grpc_Tools["Grpc.Tools<br/>"]
        nuget_Grpc_AspNetCore["Grpc.AspNetCore<br/>"]
        nuget_Grpc_AspNetCore_Web["Grpc.AspNetCore.Web<br/>"]
        nuget_Grpc_Net_Common["Grpc.Net.Common<br/>"]
        nuget_Grpc_Net_ClientFactory["Grpc.Net.ClientFactory<br/>"]
    end
    subgraph OpenTelemetry["OpenTelemetry"]
        nuget_OpenTelemetry_Exporter_OpenTelemetryProtocol["OpenTelemetry.Exporter.OpenTelemetryProtocol<br/>"]
        nuget_OpenTelemetry_Extensions_Hosting["OpenTelemetry.Extensions.Hosting<br/>"]
        nuget_OpenTelemetry["OpenTelemetry<br/>"]
        nuget_OpenTelemetry_Exporter_Prometheus_AspNetCore["OpenTelemetry.Exporter.Prometheus.AspNetCore<br/>"]
        nuget_OpenTelemetry_Instrumentation_AspNetCore["OpenTelemetry.Instrumentation.AspNetCore<br/>"]
    end
    subgraph DotNext["DotNext"]
        nuget_DotNext["DotNext<br/>"]
        nuget_DotNext_IO["DotNext.IO<br/>"]
        nuget_DotNext_Threading["DotNext.Threading<br/>"]
        nuget_DotNext_Unsafe["DotNext.Unsafe<br/>"]
    end
    subgraph Eventuous["Eventuous"]
        nuget_Eventuous_Testing["Eventuous.Testing<br/>"]
        nuget_Eventuous_Application["Eventuous.Application<br/>"]
        nuget_Eventuous_Extensions_AspNetCore["Eventuous.Extensions.AspNetCore<br/>"]
        nuget_Eventuous_Extensions_DependencyInjection["Eventuous.Extensions.DependencyInjection<br/>"]
    end
    subgraph Google["Google"]
        nuget_Google_Protobuf["Google.Protobuf<br/>"]
        nuget_Google_Cloud_Storage_V1["Google.Cloud.Storage.V1<br/>"]
        nuget_Google_Api_CommonProtos["Google.Api.CommonProtos<br/>"]
    end
    subgraph EventStore["EventStore"]
        nuget_EventStore_Client["EventStore.Client<br/>"]
        nuget_EventStore_Client_Grpc_Streams["EventStore.Client.Grpc.Streams<br/>"]
    end
    subgraph FluentAssertions["FluentAssertions"]
        nuget_FluentAssertions["FluentAssertions<br/>"]
        nuget_FluentAssertions_Analyzers["FluentAssertions.Analyzers<br/>"]
    end
    subgraph Polly["Polly"]
        nuget_Polly["Polly<br/>"]
        nuget_Polly_Core["Polly.Core<br/>"]
    end
    subgraph TestableIO["TestableIO"]
        nuget_TestableIO_System_IO_Abstractions["TestableIO.System.IO.Abstractions<br/>"]
        nuget_TestableIO_System_IO_Abstractions_TestingHelpers["TestableIO.System.IO.Abstractions.TestingHelpers<br/>"]
    end
    subgraph MudBlazor["MudBlazor"]
        nuget_MudBlazor["MudBlazor<br/>"]
        nuget_MudBlazor_Markdown["MudBlazor.Markdown<br/>"]
    end
    subgraph FluentStorage["FluentStorage"]
        nuget_FluentStorage["FluentStorage<br/>"]
        nuget_FluentStorage_AWS["FluentStorage.AWS<br/>"]
    end