graph TD
    03_Testing_RealTime_fromsrc["03_Testing.RealTime_fromsrc\n(Presentation)"]
    Algo["Algo\n(Engine)"]
    03_Testing_RealTime_fromsrc --> Algo
    Charting_Interfaces["Charting.Interfaces\n(Unclassified)"]
    Algo --> Charting_Interfaces
    BusinessEntities["BusinessEntities\n(DataAccess)"]
    Charting_Interfaces --> BusinessEntities