graph TD
    01_Candles_Realtime["01_Candles.Realtime\n(Presentation)"]
    Algo["Algo\n(Engine)"]
    01_Candles_Realtime --> Algo
    Configuration["Configuration\n(Infrastructure)"]
    Algo --> Configuration
    Messages["Messages\n(DataAccess)"]
    Configuration --> Messages