graph TD
    02_Testing_Optimization["02_Testing.Optimization\n(Presentation)"]
    Algo["Algo\n(Engine)"]
    02_Testing_Optimization --> Algo
    Configuration["Configuration\n(Infrastructure)"]
    Algo --> Configuration
    Messages["Messages\n(DataAccess)"]
    Configuration --> Messages