graph TD
    01_Candles_Realtime_fromsrc["01_Candles.Realtime_fromsrc\n(Presentation)"]
    Algo["Algo\n(Engine)"]
    01_Candles_Realtime_fromsrc --> Algo
    Configuration["Configuration\n(Infrastructure)"]
    Algo --> Configuration
    Messages["Messages\n(DataAccess)"]
    Configuration --> Messages