graph LR
    subgraph Microsoft["Microsoft"]
        nuget_Microsoft_Extensions_ServiceDiscovery_Yarp["Microsoft.Extensions.ServiceDiscovery.Yarp<br/>"]
        nuget_Microsoft_AspNetCore_Authentication_OpenIdConnect["Microsoft.AspNetCore.Authentication.OpenIdConnect<br/>"]
        nuget_Microsoft_AspNetCore_Identity_EntityFrameworkCore["Microsoft.AspNetCore.Identity.EntityFrameworkCore<br/>"]
        nuget_Microsoft_AspNetCore_Identity_UI["Microsoft.AspNetCore.Identity.UI<br/>"]
        nuget_Microsoft_EntityFrameworkCore_Tools["Microsoft.EntityFrameworkCore.Tools<br/>"]
        nuget_Microsoft_Web_LibraryManager_Build["Microsoft.Web.LibraryManager.Build<br/>"]
        nuget_Microsoft_Extensions_ApiDescription_Server["Microsoft.Extensions.ApiDescription.Server<br/>"]
        nuget_Microsoft_AspNetCore_Components_Web["Microsoft.AspNetCore.Components.Web<br/>"]
        Microsoft_more["... +16 more"]
    end
    subgraph Aspire["Aspire"]
        nuget_Aspire_Azure_AI_OpenAI["Aspire.Azure.AI.OpenAI<br/>"]
        nuget_Aspire_Npgsql_EntityFrameworkCore_PostgreSQL["Aspire.Npgsql.EntityFrameworkCore.PostgreSQL<br/>"]
        nuget_Aspire_Hosting_RabbitMQ["Aspire.Hosting.RabbitMQ<br/>"]
        nuget_Aspire_Hosting_Redis["Aspire.Hosting.Redis<br/>"]
        nuget_Aspire_Hosting_PostgreSQL["Aspire.Hosting.PostgreSQL<br/>"]
        nuget_Aspire_Hosting_Azure_CognitiveServices["Aspire.Hosting.Azure.CognitiveServices<br/>"]
        nuget_Aspire_Hosting_Yarp["Aspire.Hosting.Yarp<br/>"]
        nuget_Aspire_Npgsql["Aspire.Npgsql<br/>"]
        Aspire_more["... +2 more"]
    end
    subgraph OpenTelemetry["OpenTelemetry"]
        nuget_OpenTelemetry_Exporter_OpenTelemetryProtocol["OpenTelemetry.Exporter.OpenTelemetryProtocol<br/>"]
        nuget_OpenTelemetry_Extensions_Hosting["OpenTelemetry.Extensions.Hosting<br/>"]
        nuget_OpenTelemetry_Instrumentation_AspNetCore["OpenTelemetry.Instrumentation.AspNetCore<br/>"]
        nuget_OpenTelemetry_Instrumentation_GrpcNetClient["OpenTelemetry.Instrumentation.GrpcNetClient<br/>"]
        nuget_OpenTelemetry_Instrumentation_Http["OpenTelemetry.Instrumentation.Http<br/>"]
        nuget_OpenTelemetry_Instrumentation_Runtime["OpenTelemetry.Instrumentation.Runtime<br/>"]
    end
    subgraph CommunityToolkit["CommunityToolkit"]
        nuget_CommunityToolkit_Aspire_OllamaSharp["CommunityToolkit.Aspire.OllamaSharp<br/>"]
        nuget_CommunityToolkit_Aspire_Hosting_Ollama["CommunityToolkit.Aspire.Hosting.Ollama<br/>"]
        nuget_CommunityToolkit_Maui["CommunityToolkit.Maui<br/>9.1.1"]
        nuget_CommunityToolkit_Mvvm["CommunityToolkit.Mvvm<br/>8.3.2"]
    end
    subgraph Grpc["Grpc"]
        nuget_Grpc_Net_ClientFactory["Grpc.Net.ClientFactory<br/>"]
        nuget_Grpc_Tools["Grpc.Tools<br/>, 2.69.0"]
        nuget_Grpc_AspNetCore["Grpc.AspNetCore<br/>"]
        nuget_Grpc_Net_Client["Grpc.Net.Client<br/>2.67.0"]
    end
    subgraph Duende["Duende"]
        nuget_Duende_IdentityServer_AspNetIdentity["Duende.IdentityServer.AspNetIdentity<br/>"]
        nuget_Duende_IdentityServer_EntityFramework["Duende.IdentityServer.EntityFramework<br/>"]
        nuget_Duende_IdentityServer_Storage["Duende.IdentityServer.Storage<br/>"]
        nuget_Duende_IdentityServer["Duende.IdentityServer<br/>"]
    end
    subgraph Asp["Asp"]
        nuget_Asp_Versioning_Http_Client["Asp.Versioning.Http.Client<br/>"]
        nuget_Asp_Versioning_Http["Asp.Versioning.Http<br/>"]
        nuget_Asp_Versioning_Mvc_ApiExplorer["Asp.Versioning.Mvc.ApiExplorer<br/>"]
    end
    subgraph Pgvector["Pgvector"]
        nuget_Pgvector["Pgvector<br/>"]
        nuget_Pgvector_EntityFrameworkCore["Pgvector.EntityFrameworkCore<br/>"]
    end
    subgraph FluentValidation["FluentValidation"]
        nuget_FluentValidation["FluentValidation<br/>"]
        nuget_FluentValidation_DependencyInjectionExtensions["FluentValidation.DependencyInjectionExtensions<br/>"]
    end
    subgraph IdentityModel["IdentityModel"]
        nuget_IdentityModel_OidcClient["IdentityModel.OidcClient<br/>6.0.0"]
        nuget_IdentityModel["IdentityModel<br/>7.0.0"]
    end
    subgraph NSubstitute["NSubstitute"]
        nuget_NSubstitute["NSubstitute<br/>"]
        nuget_NSubstitute_Analyzers_CSharp["NSubstitute.Analyzers.CSharp<br/>"]
    end
    subgraph Google["Google"]
        nuget_Google_Protobuf["Google.Protobuf<br/>, 3.29.3"]
    end
    subgraph MediatR["MediatR"]
        nuget_MediatR["MediatR<br/>"]
    end
    subgraph System["System"]
        nuget_System_Reflection_TypeExtensions["System.Reflection.TypeExtensions<br/>"]
    end
    subgraph Npgsql["Npgsql"]
        nuget_Npgsql_EntityFrameworkCore_PostgreSQL["Npgsql.EntityFrameworkCore.PostgreSQL<br/>"]
    end