graph LR
    subgraph src["src"]
        src_OrchardCore_Cms_Web["OrchardCore.Cms.Web"]
        src_OrchardCore_Templates_Cms_Web["OrchardCore.Templates.Cms.Web"]
        src_OrchardCore_Templates_Mvc_Web["OrchardCore.Templates.Mvc.Web"]
        src_OrchardCore_Apis_GraphQL["OrchardCore.Apis.GraphQL"]
        src_OrchardCore_Apis_GraphQL_Abstractions["OrchardCore.Apis.GraphQL.Abstractions"]
        src_OrchardCore_Mvc_Web["OrchardCore.Mvc.Web"]
    end
    subgraph test["test"]
        test_OrchardCore_Benchmarks["OrchardCore.Benchmarks"]
    end
    subgraph DataSources
        datasource_src_Dapper_Query[("Dapper.Query")]
        datasource_src_SQL_Select[("SQL.Select")]
        datasource_src_Dapper_Execute[("Dapper.Execute")]
        datasource_src_Redis_Write[("Redis.Write")]
        datasource_src_Redis_Read[("Redis.Read")]
        datasource_src_MongoDB_Read[("MongoDB.Read")]
        datasource_src_Redis[("Redis")]
        datasource_src_EntityFramework[("EntityFramework")]
        datasource_src_SqlClient[("SqlClient")]
        datasource_src_Kafka_Topic[("Kafka.Topic")]
        datasource_src_SQL_Delete[("SQL.Delete")]
        datasource_test_Redis_Read[("Redis.Read")]
        datasource_test_Dapper_Execute[("Dapper.Execute")]
        datasource_test_Dapper_Query[("Dapper.Query")]
        datasource_test_Redis_Write[("Redis.Write")]
        datasource_test_SQL_Select[("SQL.Select")]
        datasource_test_EntityFramework[("EntityFramework")]
    end