graph LR
    subgraph Projects["Services & Projects"]
        Tests["Tests"]
    end
    subgraph APIs["API Routes"]
        url_delete(["delete"])
        url_nonexistent(["nonexistent"])
        url_TestStorage(["TestStorage"])
        url_test_example_com(["test@example.com"])
        url_TEST_EXAMPLE_COM(["TEST@EXAMPLE.COM"])
    end
    url_delete -.->|consume| Tests
    url_nonexistent -.->|consume| Tests
    url_TestStorage -.->|consume| Tests
    url_test_example_com -.->|consume| Tests
    url_TEST_EXAMPLE_COM -.->|consume| Tests