graph LR
    01_Candles_Realtime["01_Candles.Realtime\n(Presentation)"]
    Algo["Algo\n(Engine)"]
    01_Candles_Realtime --> Algo
    Charting_Interfaces["Charting.Interfaces\n(Unclassified)"]
    Algo --> Charting_Interfaces
    BusinessEntities["BusinessEntities\n(DataAccess)"]
    Charting_Interfaces --> BusinessEntities