graph TD
    02_Candles_CombineHistoryRealtime_fromsrc["02_Candles.CombineHistoryRealtime_fromsrc\n(Presentation)"]
    Algo["Algo\n(Engine)"]
    02_Candles_CombineHistoryRealtime_fromsrc --> Algo
    Configuration["Configuration\n(Infrastructure)"]
    Algo --> Configuration
    Messages["Messages\n(DataAccess)"]
    Configuration --> Messages