graph LR
    01_Testing_History["01_Testing.History\n(Presentation)"]
    Algo["Algo\n(Engine)"]
    01_Testing_History --> Algo
    Charting_Interfaces["Charting.Interfaces\n(Unclassified)"]
    Algo --> Charting_Interfaces
    BusinessEntities["BusinessEntities\n(DataAccess)"]
    Charting_Interfaces --> BusinessEntities