graph TD
    02_Candles_CombineHistoryRealtime["02_Candles.CombineHistoryRealtime\n(Presentation)"]
    Algo["Algo\n(Engine)"]
    02_Candles_CombineHistoryRealtime --> Algo
    Configuration["Configuration\n(Infrastructure)"]
    Algo --> Configuration
    Messages["Messages\n(DataAccess)"]
    Configuration --> Messages