graph LR
    02_Testing_Optimization["02_Testing.Optimization\n(Presentation)"]
    Algo["Algo\n(Engine)"]
    02_Testing_Optimization --> Algo
    Charting_Interfaces["Charting.Interfaces\n(Unclassified)"]
    Algo --> Charting_Interfaces
    BusinessEntities["BusinessEntities\n(DataAccess)"]
    Charting_Interfaces --> BusinessEntities