graph LR
    library["Library (17)"]
    test["Test (10)"]
    connector["Connector (7)"]
    tool["Tool (3)"]
    desktopapp["Desktopapp (1)"]
    test -->|22| library
    connector -->|14| library
    library -->|1| tool
    library -->|1| test