graph LR
    subgraph application["Application"]
        akka_net_SerializationBenchmarks["SerializationBenchmarks"]
        akka_net_Akka_Benchmarks["Akka.Benchmarks"]
        akka_net_Akka_Cluster_Benchmarks["Akka.Cluster.Benchmarks"]
        akka_net_RemotePingPong["RemotePingPong"]
        akka_net_Akka_Cluster_Cpu_Benchmark["Akka.Cluster.Cpu.Benchmark"]
        akka_net_PingPong["PingPong"]
        akka_net_SpawnBenchmark["SpawnBenchmark"]
        akka_net_TimeServer["TimeServer"]
        akka_net_System1["System1"]
        akka_net_System2["System2"]
        akka_net_Shared["Shared"]
        akka_net_ClusterSharding_Node["ClusterSharding.Node"]
        akka_net_ShoppingCart["ShoppingCart"]
        akka_net_HelloAkka["HelloAkka"]
        akka_net_Routing["Routing"]
        akka_net_HelloWorld["HelloWorld"]
        akka_net_ChatServer["ChatServer"]
        akka_net_AppConfig["AppConfig"]
        akka_net_FaultTolerance["FaultTolerance"]
    end
    ext_library(["Library (9)"])
    akka_net_System1 --> akka_net_Shared
    akka_net_System2 --> akka_net_Shared
    akka_net_SerializationBenchmarks -.-> ext_library
    akka_net_Akka_Benchmarks -.-> ext_library
    akka_net_Akka_Cluster_Benchmarks -.-> ext_library
    akka_net_RemotePingPong -.-> ext_library
    akka_net_Akka_Cluster_Cpu_Benchmark -.-> ext_library
    akka_net_PingPong -.-> ext_library
    akka_net_SpawnBenchmark -.-> ext_library
    akka_net_TimeServer -.-> ext_library
    akka_net_System1 -.-> ext_library
    akka_net_System2 -.-> ext_library
    akka_net_Shared -.-> ext_library
    akka_net_ClusterSharding_Node -.-> ext_library
    akka_net_ShoppingCart -.-> ext_library
    akka_net_HelloAkka -.-> ext_library
    akka_net_Routing -.-> ext_library
    akka_net_HelloWorld -.-> ext_library
    akka_net_ChatServer -.-> ext_library
    akka_net_FaultTolerance -.-> ext_library