graph LR
    subgraph Projects["Services & Projects"]
        Akka_AspNetCore["Akka.AspNetCore"]
        Akka_Docs_Tests["Akka.Docs.Tests"]
        Akka_Persistence_Custom["Akka.Persistence.Custom"]
        Samples_Akka_AspNetCore["Samples.Akka.AspNetCore"]
    end
    subgraph Database["Database / Storage"]
        table_snapshot[("snapshot")]
        table_event_journal[("event_journal")]
        table_journal_metadata[("journal_metadata")]
    end
    subgraph APIs["API Routes"]
        route_api__controller_(["api/[controller]"])
        route__(["/"])
        url_http___example_com_eventstream(["http://example.com/eventstream"])
    end
    Akka_Persistence_Custom ==>|write| table_snapshot
    Akka_Persistence_Custom ==>|write| table_event_journal
    table_event_journal -.->|read| Akka_Persistence_Custom
    Akka_Persistence_Custom ==>|write| table_journal_metadata
    table_journal_metadata -.->|read| Akka_Persistence_Custom
    Akka_AspNetCore ==>|expose| route_api__controller_
    Samples_Akka_AspNetCore ==>|expose| route__
    url_http___example_com_eventstream -.->|consume| Akka_Docs_Tests