graph TD
    subgraph sg_Presentation["Presentation (1)"]
        SymbolLookup["SymbolLookup"]
    end
    subgraph sg_DataAccess["DataAccess (1)"]
        Akka["Akka"]
    end
    SymbolLookup --> Akka