graph LR
    subgraph Projects["Services & Projects"]
        QuantConnect["QuantConnect"]
    end
    subgraph APIs["API Routes"]
        url_https___api_tournament_crunchdao_com_v2_rounds__current(["https://api.tournament.crunchdao.com/v2/rounds/@current"])
    end
    url_https___api_tournament_crunchdao_com_v2_rounds__current -.->|consume| QuantConnect